name: Terraform Create Repo

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}  # Use the PAT here
          TF_VAR_github_owner: ${{ github.repository_owner }}